name: wintershop
version: "1.0"
config-version: 2

profile: wintershop

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"

models:
  wintershop:
    bronze:
      +schema: prod
      +materialized: table

    silver:
      +materialized: table

    gold:
      +materialized: table